version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-python-django
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # use pipenv to install dependencies
             pip3 install -r requirements.txt
             python3 manage.py test
          #  sudo pip install pipenv
          #  pipenv install

